# fly.toml app configuration file generated for my-remix-app-cool-haze-9069 on 2024-10-06T18:14:07+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-remix-app-cool-haze-9069'
primary_region = 'nrt'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
